stages:
  - build
  - deploy

build_source:
  only: ["0.10.0.0"]
  before_script:
    - export http_proxy=$proxy
    - export https_proxy=$ssl_proxy
    - sudo apt-get update
    - sudo apt-get install -y qq maven
    - mkdir -p /root/.m2 && echo """<settings><proxies><proxy><id>http-proxy</id><active>true</active><protocol>http</protocol><host>$proxy_url</host><port>$proxy_port</port></proxy><proxy><id>https-proxy</id><active>true</active><protocol>https</protocol><host>$proxy_url</host><port>$proxy_port</port></proxy></proxies></settings>""" >> /root/.m2/settings.xml
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - mvn clean package
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/target/kafka-connect-elasticsearch-3.2.0-SNAPSHOT-package"

move_artifacts:
  only: ["0.10.0.0"]
  stage: deploy
  script:
    - cp -R $CI_PROJECT_DIR/target/kafka-connect-elasticsearch-3.2.0-SNAPSHOT-package /mnt/container-volumes/connect/